module.exports = {
    NODE_ENV: process.env.NODE_ENV,
    PORT_ADDRESS: process.env.PORT, 
    SALT: process.env.SALT,
    CLIENT_URI: process.env.CLIENT_URI,
    MONGODB_URI: process.env.MONGODB_URI,
    PASS: process.env.PASS,
    DBNAME: process.env.DBNAME,
    EMAIL_FROM: process.env.EMAIL_FROM,
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_LIFE: process.env.JWT_LIFE,
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    JWT_ACCESS_TOKEN_KEY: process.env.JWT_ACCESS_TOKEN_KEY,
    JWT_ACCESS_TOKEN_LIFE: process.env.JWT_ACCESS_TOKEN_LIFE,
    JWT_REFRESH_TOKEN_KEY: process.env.JWT_REFRESH_TOKEN_KEY,
    JWT_REFRESH_TOKEN_LIFE: process.env.JWT_REFRESH_TOKEN_LIFE,
}